/**
 * Cloudflare Workers — GitHub OAuth proxy for the zf-to-ics extension
 *
 * Handles the server-side steps of the GitHub OAuth flow so that the
 * client_secret never ships inside the browser extension.
 *
 * Required environment variables (set via `wrangler secret put` or the
 * Cloudflare dashboard → Workers → Settings → Variables & Secrets):
 *   GITHUB_CLIENT_ID     — GitHub OAuth App client ID
 *   GITHUB_CLIENT_SECRET — GitHub OAuth App client secret
 *
 * Routes:
 *   GET /oauth/github/authorize  — initiates the OAuth flow
 *   GET /oauth/github/callback   — handles the GitHub redirect
 */

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (request.method === "GET" && url.pathname === "/oauth/github/authorize") {
      return handleAuthorize(url, env);
    }

    if (request.method === "GET" && url.pathname === "/oauth/github/callback") {
      return handleCallback(url, env);
    }

    return new Response("Not Found", { status: 404 });
  },
};

/**
 * Route 1: GET /oauth/github/authorize
 *
 * Expected query parameters:
 *   ext_id — Chrome extension ID, used to construct the chromiumapp.org
 *             redirect URI that chrome.identity.launchWebAuthFlow intercepts
 *   state  — cryptographically random nonce generated by the extension
 *             (for CSRF protection; returned unchanged after the flow)
 *
 * Encodes ext_id into the `state` forwarded to GitHub so that the callback
 * handler knows where to redirect without storing server-side session state.
 */
function handleAuthorize(url, env) {
  const extId = url.searchParams.get("ext_id");
  const nonce = url.searchParams.get("state");

  if (!extId || !nonce) {
    return new Response(
      "Missing required query parameters: ext_id, state",
      { status: 400, headers: { "Content-Type": "text/plain" } },
    );
  }

  // Encode ext_id + original nonce as the state forwarded to GitHub.
  // btoa is available in the Workers runtime.
  const statePayload = btoa(JSON.stringify({ ext_id: extId, nonce }));

  const githubParams = new URLSearchParams({
    client_id: env.GITHUB_CLIENT_ID,
    scope: "gist",
    state: statePayload,
    redirect_uri: new URL("/oauth/github/callback", url.origin).toString(),
  });

  return Response.redirect(
    `https://github.com/login/oauth/authorize?${githubParams}`,
    302,
  );
}

/**
 * Route 2: GET /oauth/github/callback
 *
 * GitHub redirects here with:
 *   code  — short-lived authorization code to exchange for an access_token
 *   state — the encoded payload set in handleAuthorize (ext_id + nonce)
 *
 * This handler:
 *   1. Decodes the state to recover ext_id and the original nonce
 *   2. Exchanges the code for an access_token via the GitHub API
 *   3. Redirects to https://<ext_id>.chromiumapp.org/ with the access_token
 *      and nonce appended as query parameters — Chrome intercepts this URL
 *      and resolves the chrome.identity.launchWebAuthFlow promise in the
 *      extension popup.
 */
async function handleCallback(url, env) {
  const code = url.searchParams.get("code");
  const state = url.searchParams.get("state");

  if (!code || !state) {
    return new Response(
      "Missing required query parameters: code, state",
      { status: 400, headers: { "Content-Type": "text/plain" } },
    );
  }

  // Decode the state payload that was set in handleAuthorize.
  let extId, nonce;
  try {
    const payload = JSON.parse(atob(state));
    extId = payload.ext_id;
    nonce = payload.nonce;
    if (!extId || !nonce) throw new Error("Missing fields in state payload");
  } catch {
    return new Response(
      "Invalid state parameter",
      { status: 400, headers: { "Content-Type": "text/plain" } },
    );
  }

  // Exchange the authorization code for an access_token.
  // This call uses the client_secret, which lives only in the Worker.
  let tokenData;
  try {
    const tokenResp = await fetch(
      "https://github.com/login/oauth/access_token",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
        },
        body: JSON.stringify({
          client_id: env.GITHUB_CLIENT_ID,
          client_secret: env.GITHUB_CLIENT_SECRET,
          code,
          redirect_uri: new URL("/oauth/github/callback", url.origin).toString(),
        }),
      },
    );

    if (!tokenResp.ok) {
      return new Response(
        `GitHub token exchange failed with status ${tokenResp.status}`,
        { status: 502, headers: { "Content-Type": "text/plain" } },
      );
    }

    tokenData = await tokenResp.json();
  } catch (err) {
    return new Response(
      `Failed to reach GitHub: ${err.message}`,
      { status: 502, headers: { "Content-Type": "text/plain" } },
    );
  }

  if (tokenData.error) {
    return new Response(
      `GitHub OAuth error: ${tokenData.error_description ?? tokenData.error}`,
      { status: 400, headers: { "Content-Type": "text/plain" } },
    );
  }

  // Redirect back to the extension via the chromiumapp.org URL scheme.
  // chrome.identity.launchWebAuthFlow intercepts any redirect to
  // https://<ext_id>.chromiumapp.org/ and resolves the promise with that URL.
  const redirectParams = new URLSearchParams({
    access_token: tokenData.access_token,
    state: nonce, // returned so the extension can verify CSRF state
  });

  return Response.redirect(
    `https://${extId}.chromiumapp.org/?${redirectParams}`,
    302,
  );
}
